name: Saludo usando variables y secretos

on:
  workflow_dispatch
  
jobs:
  saludo-variables-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo usando variables de github y secretos
        run: echo "Hola ${{ vars.NOMBRE }}, tu contrase√±a es ${{ secrets.CONTRASENA }}"
